name = "UnitfulUS"
uuid = "7dc9378f-8956-57ef-a780-aa31cc70ff3d"
license = "MIT"
desc = "U.S. customary units for Unitful"
repo = "https://github.com/PainterQubits/UnitfulUS.jl.git"
version = "0.2.0"

[deps]
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
julia = "1"
Unitful = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

